net/DTS.HelpDesk/Areas/Admin/Models/FAQ.cs
using DTS.DbDescriptionUpdater;
using Microsoft.AspNet.Identity;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace DTS.HelpDesk.Areas.Admin.Models
{
    public class FAQ
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [DbColumnMeta(Description = "FAQ primary key.")]
        [Required(ErrorMessage = "Id required.")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        /// <value>
        /// The title.
        /// </value>
        [DbColumnMeta(Description = "FAQ title, max length 100 characters.")]
        [Required(ErrorMessage = "Title required.")]
        [MaxLength(100)]
        public string Title { get; set;  }

        /// <summary>
        /// Gets or sets the content.
        /// </summary>
        /// <value>
        /// The content.
        /// </value>
        [DbColumnMeta(Description = "FAQ content required, no max length, but should be short because this is after all an FAQ.")]
        [Required(ErrorMessage = "Content required.")]
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets the create at UTC.
        /// </summary>
        /// <value>
        /// The create at UTC.
        /// </value>
        [DbColumnMeta(Description = "UTC timestamp when FAQ was created.")]
        public DateTime CreateAtUtc { get; set; }

        /// <summary>
        /// Gets or sets the updated at UTC.
        /// </summary>
        /// <value>
        /// The updated at UTC.
        /// </value>
        [DbColumnMeta(Description = "UTC timestamp when FAQ was last modified.")]       
        public DateTime UpdatedAtUtc { get; set; }

        /// <summary>
        /// Gets or sets the views.
        /// </summary>
        /// <value>
        /// The views.
        /// </value>
        [DbColumnMeta(Description = "Total number of views / clicks.")]
        public int Views { get; set; }

        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        /// <value>
        /// The user identifier.
        /// </value>
        [DbColumnMeta(Description = "Foreign key of user that created or modified the FAQ.")]       
         public string UserId { get; set; }

        [DbColumnMeta(Description = "Bool that sets published state of FAQ.")]
        public bool IsPublished { get; set; }

        /// <summary>
        /// Gets or sets the user.
        /// </summary>
        /// <value>
        /// The user.
        /// </value>
        public virtual ApplicationUser User { get; set; }


        public FAQ() { }
        public FAQ(FAQViewModel item)
        {
            this.Id = item.Id;
            this.Title = item.Title;
            this.Content = item.Content;
            this.CreateAtUtc = item.CreateAtUtc;
            this.UpdatedAtUtc = item.UpdatedAtUtc;
            this.Views = item.Views;
            this.UserId = item.UserId;
            //this.User = user;
        }



        /// <summary>
        /// Updates FAQ.
        /// </summary>
        /// <param name="item">The item.</param>
        /// <param name="user">The user.</param>
        public void Update(FAQViewModel item)
        {
            this.Id = item.Id;
            this.Title = item.Title;
            this.Content = item.Content;
            this.CreateAtUtc = item.CreateAtUtc;
            this.UpdatedAtUtc = item.UpdatedAtUtc;
            this.Views = item.Views;
            this.UserId = item.UserId;
            this.IsPublished = item.IsPublished;
        }
    }





    public class FAQViewModel
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        public string Id { get; set; }


        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        /// <value>
        /// The title.
        /// </value>
        [Display(Name = "Title")]
        [Required(ErrorMessage = "Title is required")]
        [MaxLength(100, ErrorMessage = "Title must be less than 100 characters")]
        public string Title { get; set; }


        /// <summary>
        /// Gets or sets the content.
        /// </summary>
        /// <value>
        /// The content.
        /// </value>
        [Display(Name = "Content")]
        [Required(ErrorMessage = "Content is required")]
        [AllowHtml]
        public string Content { get; set; }


        /// <summary>
        /// Gets or sets the create at UTC.
        /// </summary>
        /// <value>
        /// The create at UTC.
        /// </value>
        [Display(Name = "Created UTC")]
        [DataType(DataType.DateTime)]
        public DateTime CreateAtUtc { get; set; }


        /// <summary>
        /// Gets or sets the updated at UTC.
        /// </summary>
        /// <value>
        /// The updated at UTC.
        /// </value>
        [Display(Name = "Updated UTC")]
        [DataType(DataType.DateTime)]        
        public DateTime UpdatedAtUtc { get; set; }


        /// <summary>
        /// Gets or sets the views.
        /// </summary>
        /// <value>
        /// The views.
        /// </value>
       
        public int Views { get; set; }
        [Display(Name = "Published")]
        public bool IsPublished { get; set; }


        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        /// <value>
        /// The user identifier.
        /// </value>
        public string UserId { get; set; }

        public ApplicationUser User { get; set; }

        public string Editor
        {
            get
            {
                var editorName = this.User.FirstName + " " + this.User.LastName;
                return !string.IsNullOrWhiteSpace(editorName) ? editorName : this.User.Email;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FAQViewModel"/> class.
        /// </summary>
        public FAQViewModel()
        {
            this.Id = Guid.NewGuid().ToString();
            this.UserId = HttpContext.Current.User.Identity.GetUserId();
            this.CreateAtUtc = DateTime.UtcNow;
            this.UpdatedAtUtc = DateTime.UtcNow;
            this.Views = 0;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FAQViewModel"/> class.
        /// </summary>
        /// <param name="item">The item.</param>
        public FAQViewModel(FAQ item) 
        {
            this.Id = item.Id;
            this.Title = item.Title;
            this.Content = item.Content;
            this.CreateAtUtc = item.CreateAtUtc;
            this.UpdatedAtUtc = item.UpdatedAtUtc;
            this.Views = item.Views;
            this.UserId = item.User.Id;
            this.User = item.User;
            this.IsPublished = item.IsPublished;
        }
    }


}

net/DTS.HelpDesk/Areas/Admin/Controllers/FAQController.cs
using DTS.DataTables.MVC;
using DTS.HelpDesk.Areas.Admin.Infrastructure.Logging;
using DTS.HelpDesk.Areas.Admin.Infrastructure.Repositories;
using DTS.HelpDesk.Areas.Admin.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DTS.HelpDesk.Areas.Admin.Infrastructure.Helpers;
using System;

namespace DTS.HelpDesk.Areas.Admin.Controllers
{
    public class FAQController : AsyncBaseController
    {
        protected readonly IFAQRepository _faqRepository;

        public FAQController(ILogger logger, IFAQRepository faqRepository) : base(logger) {
            this._faqRepository = faqRepository;
        }

        #region List

        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            ViewBag.Columns = GetColumns();
            return View("Index");
        }
        
        [AllowAnonymous]
        public JsonResult GetData([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            // get all users
            var data = _faqRepository.AllIncluding(x => x.User).ToList().Select(x => new FAQViewModel(x));
            var filteredData = data;
            var searchValue = "";
            // filter data
            if (!string.IsNullOrWhiteSpace(requestModel.Search.Value))
            {
                searchValue = requestModel.Search.Value.ToLower();
                filteredData = filteredData.Where(x =>
                    x.Title.ToLower().Contains(searchValue) ||
                    x.Editor.ToLower().Contains(searchValue));
            }

            // get sorting
            var sortColumns = string.Join(", ",
                requestModel.Columns.GetSortedColumns()
                .Select(
                    x => string.Format("{0} {1}", x.Data, x.SortDirection.ToString().ToLower().Contains("asc") ? "ASC" : "DESC")
                ).ToArray());

            // get paged data
            var pagedData = filteredData
                .OrderBy(sortColumns)
                .Skip(requestModel.Start)
                .Take(requestModel.Length);

            var result = new DataTablesResponse(requestModel.Draw, pagedData, data.Count(), data.Count());
            return Json(result);
        }

        private string GetColumns()
        {
            return JsonConvert.SerializeObject(new List<ColumnHeader>() { 
                new ColumnHeader() { data = "Id", name = "", visible = true, sortable = false, width = "50px", className = "text-center"  },
                new ColumnHeader() { data = "Title", name = "Title", visible = true, sortable = true },
                new ColumnHeader() { data = "Editor", name = "Editor", visible = true, sortable = true },
                new ColumnHeader() { data = "IsPublished", name = "Published", visible = true, sortable = true, className = "text-center" },
                new ColumnHeader() { data = "Views", name = "Views", visible = true, sortable = true },
                new ColumnHeader() { data = "CreateAtUtc", name = "Created UTC", visible = true, sortable = true },
                new ColumnHeader() { data = "UpdatedAtUtc", name = "Updated UTC", visible = true, sortable = true },

            });
        }


        #endregion

        #region Create

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            AddToViewBag();
            return View("Create", new FAQViewModel());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(FAQViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                model.UserId = User.Identity.GetUserId();
                model.CreateAtUtc = DateTime.Now;
                model.UpdatedAtUtc = DateTime.Now;
                var faq = new FAQ(model);
                _faqRepository.Add(faq);
                _faqRepository.Save();
                return RedirectToAction("Index");
            }
            AddToViewBag();
            return View("Create", model);
        }

        #endregion

        #region Edit

        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            var faq = _faqRepository.Find(id);
            var model = new FAQViewModel(_faqRepository.Find(id));
            AddToViewBag();
            return View("Edit", model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FAQViewModel model, string toDo = "")
        {
            if (toDo.ToLower() == "delete") {
                _faqRepository.Delete(model.Id);
                _faqRepository.Save();
                return RedirectToAction("Index");
            }


            if (ModelState.IsValid)
            {
                var faq = _faqRepository.Find(model.Id);
                model.UserId = User.Identity.GetUserId();
                faq.Update(model);
                _faqRepository.Update(faq);
                _faqRepository.Save();
                return RedirectToAction("Index");
            }
            AddToViewBag();
            return View("Edit", model);
        }

        [HttpPost]
        public void Publish(string id)
        {
            var faq = _faqRepository.Find(id);
            faq.IsPublished = !faq.IsPublished ? true : false;
            _faqRepository.Update(faq);
            _faqRepository.Save();
        }
        #endregion



        private void AddToViewBag() {
            ViewBag.YesOrNo = new List<SelectListItem>() { 
                new SelectListItem() { Text = "No", Value = false.ToString() },
                new SelectListItem() { Text = "Yes", Value = true.ToString() }
            };

        }



    }
}

net/DTS.HelpDesk/Areas/Admin/Views/FAQ/Create.cshtml
@model DTS.HelpDesk.Areas.Admin.Models.FAQViewModel
@{
    ViewBag.Title = "Create FAQ";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">@ViewBag.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Create", "FAQ", FormMethod.Post, new { role = "form" }))
        {
            @Html.Partial("_CreateOrEdit")
        }
    </div>
</div>

@section Styles {
    @Styles.Render("~/editor/styles")
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/editor/scripts")
    <script>
        $('.txtArea').summernote({
            height: 300
        });
    </script>
}

net/DTS.HelpDesk/Areas/Admin/Views/FAQ/Edit.cshtml
@model DTS.HelpDesk.Areas.Admin.Models.FAQViewModel
@{
    ViewBag.Title = "Edit FAQ";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">@ViewBag.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Edit", "FAQ", FormMethod.Post, new { @class="editform", role = "form" }))
        {
            @Html.Partial("_CreateOrEdit")
        }
    </div>
</div>

@section Styles {
    @Styles.Render("~/editor/styles")
}


@section Scripts {
    @Scripts.Render("~/scripts/utilities")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/editor/scripts")
    @Scripts.Render("~/scripts/faq")
    <script>

        $(function () {
            dts.faq.init({
                _selector: '.delete-button',
                _title: 'Delete FAQ?',
                _message: 'Are you sure, this is irreversible.',
                _textAreaSelector: '.txtArea',
                _textAreaHeight: '300'
            });
        });
    </script>
}

net/DTS.HelpDesk/Areas/Admin/Views/FAQ/Index.cshtml
@{
    ViewBag.Title = "FAQs";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">@ViewBag.Title </h1>
    </div>
    <div class="col-lg-12">
        @Html.ActionLink("New FAQ", "Create", new { controller = "FAQ", area = "Admin" }, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

<div class="row" style="margin-top:30px;">
    <div class="col-lg-12">
        <table id="grid" class="table table-bordered table-striped table-condensed">
            <thead>
                <tr></tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>


@section Styles {
    @Styles.Render("~/styles/datatables")
    <style type="text/css">
    </style>
}

@section Scripts {
    @Scripts.Render("~/scripts/utilities")
    @Scripts.Render("~/scripts/datatables")
    @Scripts.Render("~/scripts/faqs")

    <script>
    var _dataTable;
    $(function () {
        _dataTable = dts.faqs.init({
            _tableSelector: '#grid',
            _columns: JSON.parse('@Html.Raw(ViewBag.Columns)'),
            _getUrl: '@Url.Action("GetData", new { controller = "FAQ", area = "Admin"})',
            _editUrl: '@Url.Action("Edit", new { controller = "FAQ", area = "Admin"})',
            _publishUrl: '@Url.Action("Publish", new { controller = "FAQ", area = "Admin"})'
        });
    });
    </script>
    @Html.Partial("_ichTemplates")


}

net/DTS.HelpDesk/Areas/Admin/Views/FAQ/_CreateOrEdit.cshtml
@model DTS.HelpDesk.Areas.Admin.Models.FAQViewModel

@Html.AntiForgeryToken()
@Html.ValidationSummary("", new { @class = "text-danger" })

<div class="form-group">
    @Html.LabelFor(x => x.Title)
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", placehoder = "FAQ Title" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Content)
    @Html.TextAreaFor(x => x.Content, new { @class = "form-control txtArea", placehoder = "FAQ Content", spellcheck = "true" })
</div>

<div class="form-group">
    <label class="control-label col-sm-2">Publish</label>
    <div class="col-sm-3">
        @Html.DropDownListFor(x => x.IsPublished, (IEnumerable<SelectListItem>)ViewBag.YesOrNo, new { @class = "form-control" })
    </div>
</div>


<div class="form-group"><br />
    <div class="col-sm-12">
        <button type="submit" class="btn btn-success">Save</button>
        @if (ViewContext.HttpContext.Request.Url.ToString().ToLower().Contains("edit"))
        {
            <button type="button" class="btn btn-danger delete-button">Delete</button>
        }
        @Html.ActionLink("Cancel", "Index", new { controller = "FAQ" }, new { @class = "btn" })
    </div>
</div>